### PR TITLE
Improve arch detection for ARM64EC

### PR DESCRIPTION
**Pull request by skyline75489**
Reference: https://techcommunity.microsoft.com/t5/windows-os-platform-blog/getting-to-know-arm64ec-defines-and-intrinsic-functions/ba-p/2957235

### CODE REVIEW

**Comment by skyline75489** [comment]
The whitespace changes are automatically performed by my editor. "Hide whitespace" might be a better approach to review this on GitHub

**Comment by mackron** [comment]
Thanks. This looks reasonable. The whitespace changes just look like trailing whitespace trimming so no drama there. Will get this merged soon.

**Comment by skyline75489** [comment]
Friendly ping for this PR to be merged :)

**Comment by mackron** [comment]
Sorry I haven't got to this yet. Not ignoring it. I've moved from Windows to Linux and haven't yet moved my workflow over so I'm a bit slow at the moment.

**Pull request merged**
