### PR TITLE
Fuzzer fixes, cleaned up this time

### PR DESCRIPTION
**Pull request by bobsayshilol**
A cleaned up version of #39.

### CODE REVIEW

**Comment by mackron** [comment]
I've gone ahead and pushed my changes to your branch. If you like you can re-run your tests before I merge.

By the way, thanks for putting the effort into doing everything in small commits. Makes things a lot easier to review. 👍

**Comment by bobsayshilol** [comment]
So I'm still seeing issues at:

> dr_flac.h:2360:41: runtime error: shift exponent 64 is too large for 64-bit type 'unsigned long'
> dr_flac.h:2300:71: runtime error: shift exponent 64 is too large for 64-bit type 'unsigned long'

which are due to bitCountLo being 0 in the shift on those lines. I haven't had time to reason from the code whether or not that means we could just jump straight to setting the out values, or how much of a perf hit that branch would cost in the more common case. I was going to suggest reverting b7e3d13 if it's a perf hit at all (and to avoid code duplication) since it's only ever 0 that we're shifting by an invalid amount, but at the same time https://godbolt.org/z/eu5M7c shows UB (at compile time) is not something to mess with.

I also had a look at L1 cache macros after b7e3d13 and in trying to simplify their usage in `drflac__read_rice_parts()` I managed to write it in a way that produces slightly smaller assembly across all major compilers (according to godbolt) and continues to produce the correct result from a local test, however perf wasn't profiled so it may in fact be slower. A quick proof to go with it if the logic jumps I made aren't obvious after expanding the macros:
```
(x & (riceParamMask >> setBitOffsetPlus1)) >> (bsSize - riceParam - setBitOffsetPlus1)
= (x >> (bsSize - riceParam - setBitOffsetPlus1)) & ((riceParamMask >> setBitOffsetPlus1) >> (bsSize - riceParam - setBitOffsetPlus1))
= (x >> (bsSize - riceLength)) & (riceParamMask >> (bsSize - riceParam))

Highest 'riceParam' bits of 'riceParamMask' are set, which means that shifting by 'bsSize' - 'riceParam' bits (ie how many aren't set) moves them to the bottom
==> (riceParamMask >> (bsSize - riceParam)) = lowest 'riceParam' bits set = ~((~(drflac_cache_t)0) << riceParam))

Therefore:
riceParamPart = (x >> (bsSize - riceLength)) & ~((~(drflac_cache_t)0) << riceParam))
```

> By the way, thanks for putting the effort into doing everything in small commits. Makes things a lot easier to review. :+1:

As someone who does reviews, anyone who doesn't do it that way is doing it wrong :P

**Comment by mackron** [comment]
That latest commit of yours has a performance regression so I've just reverted it for now (your original commit still exists so we can go back to it for reference). I've kept part of it in commit 7730aa1f52ee112e1d022eda1fa85ad345d4b891, but I have no idea _why_ the other parts are causing it to slow down. I will continue to look at this...

> which are due to bitCountLo being 0 in the shift

Right, I didn't actually notice that case... I've got a potential fix for this in commit fe8b2916e7cead6feaa8dd642350fa97bd60b055. It's similar to what you did with that other commit you did that I had you revert where you had a branch, only with this one it's branchless.

> since it's only ever 0 that we're shifting by an invalid amount

That's actually a good point - I didn't think of that. I would seriously doubt there would be any compile time shenanigans going on with that particular section of code, however commit fe8b2916e7cead6feaa8dd642350fa97bd60b055 has a potential fix.

That commit I did with the code duplication (b7e3d13e91eb4ce705c846b127025b6fe6c9c360) actually has a slight performance benefit, so I think I'm going to keep it for now.

**Comment by bobsayshilol** [comment]
Gah, it's been a while since I've messed with bit twiddling hacks (8d286ec is the closest I've come for a long time) and completely forgot about masking tricks like fe8b291. That'd have been a better solution than branching in 2c90ce1 for sure. And yep that fixes the UB, thanks!

I'm surprised 8d286ec gave a perf loss, but that's exactly why they always say to measure rather than speculate.

This all looks OK to me, so merge away! As a side note, I've just checked the code coverage and noticed that my simplistic fuzzer isn't hitting any of the metadata parsing or seeking code, so I'll make another fuzzer for those and see if I can get the current 60% coverage up past 90%. If you'd rather wait until that's happened before merging then that's fine, but I'm happy to open another PR if they do spot anything.

**Comment by mackron** [comment]
I don't know why that performance hit is happening - it happens when I change the scope of that riceParamMask variable. I'm suspecting it's some compiler optimization heuristics that are coming up with less optimal code generation for some reason.

I'm happy to wait before merging.

**Comment by bobsayshilol** [comment]
Ah, that was going to be my guess but I didn't want to make myself sound like an idiot lol Moving it back to its original location at the start of the function likely makes the compiler realise it can hoist the result of the shift out and precompute it in `drflac__decode_samples_with_residual__rice__simple()` (line 2386) as it's a constant that's recalculated on each call. I did consider passing it into the function since, in theory, it'd be (sort of) inlined anyway, but in the end assumed that the compiler would know better. Compilers never cease to amaze me at the optimisations they miss https://godbolt.org/z/40bdCi :P

**Comment by mackron** [comment]
That's a good point, actually. I would bet money that's what it is.

**Comment by bobsayshilol** [comment]
> EDIT: Annoyingly, I tried putting back your original optimization, except keeping the declaration of riceParamMask at the top of the function, and it's still slower... Weird. I'm giving up for now.

lol Compilers are weird. Thanks anyway for profiling it and making sure it was faster :P

I've pushed some more changes, but I don't think I'm done fuzzing just yet, and I don't think I could have made the change in 56e9369 any higher up so hopefully that's not a perf hit.

**Comment by mackron** [comment]
All of these commits are good. Thanks a lot for all of this - I can see you've put a lot of work into it. I actually had an item in my todo list to test that cuesheet stuff (that was completely untested), but it looks like you beat me to it. :)

I have also gone ahead and pushed a fix for a few compiler warnings for the 32-bit MSVC build.

**Comment by bobsayshilol** [comment]
1292a0b has opened up a new codepath for the fuzzer, so I'll leave it to do its thing. There are some other branches that aren't being hit (one in particular in the hot path https://github.com/bobsayshilol/dr_libs/blob/fuzzer-fixes-cleaned-up/dr_flac.h#L1506-L1508) but I don't see any obvious reason why it's not taking it, and also the entirety of https://github.com/bobsayshilol/dr_libs/blob/fuzzer-fixes-cleaned-up/dr_flac.h#L4615-L4725 is missed because of the branch just before it. I'll see if I can dig into it later and find out why the ogg code isn't being hit (current guess is that the fuzzer just hasn't found it yet) but since you're familiar with the code you might spot something more obvious if you take a glance.

There's also the assert for `count > 0` being hit in `drflac__read_and_seek_residual__rice()` that'll I'll minimize, and in the unencoded residual read path that 1292a0b unlocked, `unencodedBitsPerSample` can be 0 which `drflac__decode_samples_with_residual__unencoded()` doesn't like. I can't tell what's valid and what's not, so I haven't committed any fixes for either.

**Comment by bobsayshilol** [comment]
And I've just realised the reason for https://github.com/bobsayshilol/dr_libs/blob/fuzzer-fixes-cleaned-up/dr_flac.h#L1506-L1508 not being hit - I'm on 64bit so `DRFLAC_CACHE_L1_SIZE_BITS()` is 64, but it's reading a max of 32 bits. I'll fix that up when I get back.

**Comment by bobsayshilol** [comment]
So I did wonder whether or not 703551b was necessary after not seeing any branches locally in the asm, but a quick and hacky test on godbolt shows that MSVC isn't quite as smart as GCC or clang https://godbolt.org/z/DUxRIH, ie it can't tell that `f()` returns a value that's at most 'bits' bits (assuming I've got the optimisation flags right).

Here's the 2 minimized files that cause the asserts to fire. [asserts.zip](https://github.com/mackron/dr_libs/files/2364760/asserts.zip)

The ogg code not being hit was my own idiocy, but leaving that to fuzz for a while now hasn't shown anything else, and coverage shows it's hitting pretty much everything, so I think I'm finally done and this can be merged lol

**Comment by mackron** [comment]
Thanks a lot for all of this. Good catch on those Rice escape codes!

I have pushed a fix for those assertions - I'm now explicitly allowing `unencodedBitsPerSample` to be zero. The FLAC spec doesn't explicitly disallow it, so neither am I.

I don't like commit 703551b1fe7ce7a80d3a9d36db5fc01b416c97b5, though. There's just something that doesn't feel right about it - just feels too hacky or something. In any case, I've pushed my proposed solution to this one. It's more explicit, and, theoretically, a tiny bit more efficient on 64-bit caches.

Those dr_wav commits are good. Thanks!

If you're happy with those last commits I did I'm happy to go ahead and merge. Thanks a lot for all of your work on this - it's been a productive back and forth and it's made dr_flac a better product. 👍

**Comment by bobsayshilol** [comment]
> I have pushed a fix for those assertions

One of them looks fixed, but the assert at https://github.com/bobsayshilol/dr_libs/blob/fuzzer-fixes-cleaned-up/dr_flac.h#L2587 was still being hit by the `count` test in the zip. AFAICT that was coming from the check at https://github.com/bobsayshilol/dr_libs/blob/fuzzer-fixes-cleaned-up/dr_flac.h#L2670 not being applied to the seeking code, so I've added that.

> I don't like commit 703551b, though.

Ah I went for the path of least code duplication since any sane compiler can see that `DRFLAC_CACHE_L1_SIZE_BITS(bs) > 32` is true at compile time, but either works :P Why does `DRFLAC_CACHE_L1_SIZE_BITS()` take an argument by the way, seeing as `DRFLAC_CACHE_L1_SELECTION_MASK()` assumes the underlying type of the cache without a need for `bs` getting involved?

> If you're happy with those last commits I did I'm happy to go ahead and merge.

Yep, looks good to me, so if you're OK with my last one then go for merge.

**Comment by bobsayshilol** [comment]
Thanks! It's been fun :P

**Pull request merged**
