### PR TITLE
dr_wav: utility functions for computing total target write size

### PR DESCRIPTION
**Pull request by bmcdonnell-ionx**
I added a couple of utility functions for computing the total size of a target, based on provided metadata. Is the algorithm correct?

I'm working with a file system where I have to know the file size in order to create the file. That makes this a useful feature.

It looks to me like dr_wav supports reading from more types of files than it supports writing to (e.g. files w/ smpl loops), so I put `write` in the function names, to indicate it's only for that purpose.

### CODE REVIEW

**Comment by bmcdonnell-ionx** [comment]
Hmm, I think I didn't account for the ID and size of the data (sub)chunk...

http://soundfile.sapp.org/doc/WaveFormat/

**Comment by bmcdonnell-ionx** [comment]
Actually, looks like I made a bigger mistake here, in that the RIFF chunk size includes the data subchunk. I need to think some more about this.

**Comment by mackron** [comment]
I'm happy to add a helper API for this.

The `drwav_riff_chunk_size_riff()` function calculate the value of the `ChunkSize` variable in the RIFF chunk from that documentation you linked. You would you just need to call `drwav_riff_chunk_size_riff/w64()` and then add 8 for the RIFF case and 0 for the W64 case.

In your original commit here, what's the difference between `drwav_target_write_size_bytes()` and `drwav_target_write_size_bytes_riff()`? Is it just that one is 64-bit and the other is 32-bit? If so, I'd rather just have the 64-bit version just to keep it simple (programs can cast the return value if they need to).

**Comment by bmcdonnell-ionx** [comment]
> I'm happy to add a helper API for this.

Thanks for that, and your work and sharing in general. 😃

> The `drwav_riff_chunk_size_riff()` function calculate the value of the `ChunkSize` variable in the RIFF chunk from that documentation you linked. You would you just need to call `drwav_riff_chunk_size_riff/w64()` and then add 8 for the RIFF case and 0 for the W64 case.

I was starting to think that. Basically the whole file is one big RIFF chunk; and said RIFF chunk contains subchunks (currently just fmt & data). Right?

I see from the [Wikipedia RIFF page](https://en.wikipedia.org/wiki/Resource_Interchange_File_Format) that besides the RIFF ("parent") chunk type, there also exists a LIST chunk type. It's conceivable to me that future versions of dr_wav might allow writing other chunk types, so I'd be happy for this feature to be owned by dr_wav, even though it's just a simple `riff_chunk_size + 8` for now.

> In your original commit here, what's the difference between `drwav_target_write_size_bytes()` and `drwav_target_write_size_bytes_riff()`? Is it just that one is 64-bit and the other is 32-bit?

Yes.

> If so, I'd rather just have the 64-bit version just to keep it simple (programs can cast the return value if they need to).

The motivation was to allow applications to avoid the overhead of using the 64-bit integer, when it's known not to be needed, in resource constrained (embedded) environments.

**Comment by bmcdonnell-ionx** [comment]
Above I quoted

> Apparently "All files contain only the RIFF chunk at the root level..."

Is this also true of W64 files? It's not clear to me from [sony_wave64.pdf](http://www.ambisonia.com/Members/mleese/sony_wave64.pdf/).

**Comment by mackron** [comment]
I believe W64 is basically the same, only with chunk IDs changed from fourcc codes to GUIDs and size fields changed from 32 bit to 64 bit. There's other relatively minor changes, but nothing structural.

With the 32 bit thing and the _riff varient of that function, I'm just trying to be practical. The entire library uses 64 bit integers in order to seamlessly support w64 so it's not like this will prevent the use of 64 bit arithmetic entirely. Also, I'm assuming this will be called just once for each file that's written? Is it really worth the maintenance cost? I also see the opportunity for confusion over which version someone should use - almost like the difference between "init" and "open".

I don't do much embedded stuff so I apologize if I sound a bit ignorant :)

**Comment by bmcdonnell-ionx** [comment]
> With the 32 bit thing and the _riff varient of that function, I'm just trying to be practical. The entire library uses 64 bit integers in order to seamlessly support w64 so it's not like this will prevent the use of 64 bit arithmetic entirely. Also, I'm assuming this will be called just once for each file that's written? Is it really worth the maintenance cost? I also see the opportunity for confusion over which version someone should use - almost like the difference between "init" and "open".

Good points. See my latest (forced) push.

**Comment by bmcdonnell-ionx** [comment]
Please decide how you want to handle #60 WRT this function before merging this.

**Comment by mackron** [comment]
I'm happy with this implementation (I'll make a few minor style adjustments myself). We'll stick with `totalSampleCount` for consistency with the other writing APIs and then review it later if necessary.

**Comment by bmcdonnell-ionx** [comment]
More changes coming...

**Comment by bmcdonnell-ionx** [comment]
Force pushed again. I think there's an edge case I hadn't quite covered.

I infer from the following that the stated size of the RIFF chunk in the RIFF header should include the padding of any subchunks. It's not explicitly clear from the text, but if you have 2 padded subchunks, and you don't include the subchunk padding in the parent chunk size, then your parent chunk size would be wrong.

From [riffmci.pdf](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/riffmci.pdf):

| _Part_ | _Description_
| ---- | ------------
| `ckID` | A four-character code that identifies the representation of the chunk data `data`. A program reading a RIFF file can skip over any chunk whose chunk ID it doesn't recognize; it simply skips the number of bytes specified by ckSize plus the pad byte, if present.
| `ckSize` | A 32-bit unsigned value identifying the size of `ckData`. This size value does not include the size of the `ckID` or `ckSize` fields or the pad byte at the end of `ckData`.
| `ckData` | Binary data of fixed or variable size. The start of `ckData` is word-aligned with respect to the start of the RIFF file. If the chunk size is an odd number of bytes, a pad byte with value zero is written after `ckData`. Word aligning improves access speed (for chunks resident in memory) and maintains compatibility with EA IFF. The `ckSize` value does not include the pad byte.

**Comment by mackron** [comment]
Oh yeah, I forgot about the padding stuff. You'll definitely want to handle that.

**Comment by bmcdonnell-ionx** [comment]
Am I handling it correctly as it stands now?

**Comment by mackron** [comment]
I think this is right. The only confusing part is whether or not the padding byte should be included in the size field in the main RIFF chunk. I think it should be included, which I think you've done right.

I'm happy to merge this as is. Thanks for fixing up those comments by the way!

**Comment by mackron** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
