### PR TITLE
Fuzzer fixes

### PR DESCRIPTION
**Pull request by bobsayshilol**
These are a set of changes to fix issues found by running a very simple fuzzer on dr_flac.h and dr_mp3.h. Originally this was only meant for dr_mp3.h as I saw it's inclusion in the SDL_sound rewrite, however the fuzzer had other ideas and thought dr_flac.h was more interesting :P

I'll leave my fuzzers running overnight and see if they pick up any more low hanging fruit, but I thought it'd be best to check these in now to make sure I'm complying with style guides etc...

### CODE REVIEW

**Comment by mackron** [comment]
OK, I'm just reviewing this and there's a few things to sort out and a few questions.

Commit 5a06c3ec62099526a867808f1cff05ceb47abd9e: What's the rationale for this? The point of that assert is to show that dr_flac will never perform a relative seek of zero bytes. If dr_flac is doing this, it's a bug, and I'd rather fix it at a higher level. Do you have a reproducible use case for this?

Commit: 2c90ce1332ff8afb967261586be757c97176a850: This causes an unacceptable performance regression and I won't be merging it in it's current state. See screenshots below for my profiling tests. The problem is that the bit streaming and rice decoding stuff are the hottest functions in the library and small changes can cause large regressions. A few things:
- The changes to `DRFLAC_CACHE_L1_BITS_REMAINING`, `DRFLAC_CACHE_L1_SELECTION_MASK` and `DRFLAC_CACHE_L1_SELECT_AND_SHIFT` are good.
- The change to `DRFLAC_CACHE_L1_SELECTION_SHIFT` is not as good. I don't like the conditional - I think I would rather check if `riceParam == 0` at a higher level and do a more optimized solution. Also, on line 2284, I can't see how the 0 check is necessary because `riceLength` will never be 0 since it's set to `setBitOffsetPlus1 + riceParam` (emphasis on the **Plus1**).
- Regarding your comment about `consumedBits` blowing out - do you have a reproducible use case for this? What changes specifically contribute to the fix for this particular issue? This feels like it could be the result of a higher level bug, but I could be wrong... I want to understand exactly _why_ this is happening.
- I will continue looking at the performance issues and get back to you.


Profiling (lower percentages is better).

master branch:
image

fuzzer-fixes branch:
image

**Comment by bobsayshilol** [comment]
> Have you noticed any performance regressions with these changes by the way?

I honestly didn't have performance in mind when I was fuzzing, just making sure that a rouge file couldn't cause nasty issues.


> Commit 5a06c3e: What's the rationale for this? The point of that assert is to show that dr_flac will never perform a relative seek of zero bytes. If dr_flac is doing this, it's a bug, and I'd rather fix it at a higher level. Do you have a reproducible use case for this?

Ah, that's exactly what I _was_ seeing: seeking current by 0B. I'll attach the minimized test case... zipped because TIL github doesn't allow arbitrary data uploads. [0_seek.zip](https://github.com/mackron/dr_libs/files/2346327/0_seek.zip)


> Commit: 2c90ce1: This causes an unacceptable performance regression and I won't be merging it in it's current state.

That's fair. I knew at the time that I should have broken that commit up, but my excuse is that it was late and a Sunday :P

I'll cherrypick both commits out of this branch and split 2c90ce1 up into its component parts.

**Comment by bobsayshilol** [comment]
I don't know how well github deals with force pushes to pull request branches (I can imagine the commit links would easily break!), so I've opted for pulling the good commits into another branch (https://github.com/bobsayshilol/dr_libs/commits/fuzzer-fixes-cleaned-up) and cleaned up the commit messages to state which file they change (whoops!), along with one more from last night's fuzzing and the good parts of 2c90ce1. I'll rerun the fuzzer on that HEAD (plus 5a06c3e locally so it doesn't trip over those) in a bit and see if I can find if/why the rest of 2c90ce1 was necessary.

**Comment by r-lyeh** [comment]
`I don't know how well github deals with force pushes to pull request branches` 
I've verified that works for me! no probs so far :D in fact, I even delete the repo before the owner accepts the PR even! The code is safe somewhere deep in github servers :)

**Comment by bobsayshilol** [comment]
It took a while but here's the repro case for the overflows. It reproduces on both master and fuzzer-fixes, and seems a lot slower than the other cases too. [overflow.zip](https://github.com/mackron/dr_libs/files/2346668/overflow.zip)

**Comment by mackron** [comment]
> Ah, that's exactly what I was seeing: seeking current by 0B.

OK, so with this one it's trying to seek past a zero length Ogg page (not including header) which is actually a valid Ogg page, so I accept your proposed changes. Thanks!

> It took a while but here's the repro case for the overflows.

Thanks for that. I have fixed that bug, but I can't push the change to your fuzzer-fixes-cleaned-up branch because I don't have permissions. Are you able to give me write permissions to that branch, or open a fresh pull request so I can write to it?

The trying-to-shift-by-exactly-64 errors are due to `riceParam` in `drflac__read_rice_parts()` being set to 0. I've done a riceParam=0 optimized path for this which avoids a performance regression at the expense of some code duplication. Again, I can't push this to your branch until you open a fresh a pull request.

I have not looked at the `drflac__calculate_prediction_32()` issue, and I'm not sure I care enough. I'm doubting this would happen in the real world with a properly encoded FLAC stream.

I'm happy with all of the changes in the fuzzer-fixes-cleaned-up branch by the way. If you open up a fresh pull request, I can push my changes and, if you like, you can re-run your tests just to double check that the issues have been fixed for real.

Thanks for all your work on this!

**Comment by bobsayshilol** [comment]
> OK, so with this one it's trying to seek past a zero length Ogg page (not including header) which is actually a valid Ogg page, so I accept your proposed changes. Thanks!

I won't resurrect that commit onto the cleaned up branch since I feel my commit message didn't adequately explain why it was necessary, but feel free to reapply it or your own more descriptive one along with the overflow fix.

> I have not looked at the `drflac__calculate_prediction_32()` issue, and I'm not sure I care enough. I'm doubting this would happen in the real world with a properly encoded FLAC stream.

Ah, what I meant was that it's fine to leave that as-is since a fair few number of commercial audio libraries hit those same sort of overflow issues when compiled with UBSan enabled (using goldmaster game data no less!), so there's little reason to care :P

> I'm happy with all of the changes in the fuzzer-fixes-cleaned-up branch by the way. If you open up a fresh pull request, I can push my changes and, if you like, you can re-run your tests just to double check that the issues have been fixed for real.

I'll close this one and open up a new pull request now so that they can all be merged. Thanks!

> Thanks for all your work on this!

No problem, I find this sort of thing fun :P Thanks for giving this a proper review rather than accepting it blindly.

**Pull request closed without merging**
