### PR TITLE
dr_wav: Smpl chunk support

### PR DESCRIPTION
**Pull request by mgambrell**
support smpl chunk and one sample loop: this suffices for most looped wave files
I didn't test this extensively. If you're interested in the functionality, maybe you can test it and let me know how it looks and I'll debug it further if theres any trouble

### CODE REVIEW

**Comment by mackron** [comment]
Thanks for this. I never realized that the "data" chunk could sometimes not be the last chunk - needed to look it up, and indeed it appears to be true.

A few comments and questions:
- What is the smpl chunk? What is it's purpose, and what does it do? I know nothing about it.
- That seek to the data chunk needs to be changed to be 64-bit friendly. It needs to be put into a loop since onSeek() uses 32-bit integers.
- In the second commit (7d98f64824bafa3cab9bef60144ee2d1b9c1beeb) you are supporting the riff container, but not the w64 container. I won't merge until it's consistent between the two (dr_wav advertises seamless support for w64).
- A small thing - the `drwav_smpl_loop smpl_loop;` declaration needs to be renamed to `smplLoop` for consistency.

I will review this in more detail when I get a chance. I may also push some changes to your pull request branch.

Thanks!

**Comment by mgambrell** [comment]
Oops, I had made it 64bit friendly in my other branch, but it was invisible

I don't have a w64 format SMPL chunk to test, but OK, I think I probably did it correctly

smpl chunk is chiefly (as far as I'm concerned) used for setting the loop points in video game sound effects. Sometimes you don't want the entire sound to loop but want an attack section and then an indefinitely sustaining section. (It's also used by synthesizers for many more obscure purposes.) I'll attach a wave file example so you can see the significance. The 36000 sample file loops from 18000->36000 after playing the "attack" (the activation part of the sound) from 0->18000

[dash_loop.zip](https://github.com/mackron/dr_libs/files/2380836/dash_loop.zip)

**Comment by mackron** [comment]
So I've gone ahead and checked this out and it's unfortunately most of my test vectors fail with these changes. We need to take a step back and reassess how we'll do this. I'm going to propose that we break it down into parts:

1) I think the chunk callback system should be done first. This will implement the necessary logic for enumerating over all chunks, including cases where the "data" chunk is not the last one. This is necessary prerequisite for smpl, so I feel like it makes sense to get this done first.
2) Augment the chunk enumeration logic to add built-in support for smpl.
3) Update drwav_read_*() to seamlessly support reading smpl based files.

Sound like a reasonable plan to you? I will work on the chunk callback system.

**Comment by mgambrell** [comment]
Sounds fine to me, but point 3 isn't important for me. I don't need that. I don't understand anyone who needs drwav_read_* so I can't guess whether that behaviour for loops would be useful to them. But I would caution you that the semantics may be kind of arbitrary: there may be multiple SMPL chunks, each with multiple loops... what then? Interpreting the SMPL loops is kind of application-specific, so that's why I'm not sure it makes sense for you to interpret them in the library. That said, there is a very normal application, which is the one-chunk one-loop case. That's why reading that one case out and parking it for easy access is reasonable.

I don't think theres any other way I can help you at this point (I understand why the chunk callbacks needs to be something you design yourself). But I'll be glad to test your changes when I see them.

**Comment by mackron** [comment]
Yeah I was actually thinking about that just after I wrote it (regarding drwav_read_*). I might abandon that idea actually...

In case you're curious, I pushed a change which sets up some infrastructure for the chunk enumeration logic (not got the chunk callback stuff in yet). Your branch is conflicting, but I'll probably abandon this pull request and just do the smpl stuff manually and then get you to test. Will keep you updated.

**Comment by mgambrell** [comment]
That's fine, you can toss my stuff in the garbage. Just check inspect the SMPL stuff, it might be useful to you as a living reference example.

**Comment by mackron** [comment]
I changed my mind slightly and went ahead and added support for smpl chunks now. Mostly the same as your original implementation, only this time the loop data is part of the `drwav_smpl` structure and allows more than 1, up to a maximum of `DRWAV_MAX_SMPL_LOOPS`. It's sitting in the wav/dev branch - are you able to try that out when you get a chance?

**Comment by mackron** [comment]
OK I've gone ahead and implemented the chunk callback system. It's all in the "wav/dev" branch. It's similar to your original changes, but I've introduced a new extended API for each of the initialization APIs: drwav_init_ex(), drwav_open_ex(), etc.

The chunk callback system can require backwards seeking, so I've also added a flags parameter to the new APIs to control this. Currently there is only one flag, called DRWAV_SEQUENTIAL which basically terminates the chunk loop at the "data" chunk (the same behaviour as before).

I'm going to go ahead and close that other pull request and bring that conversation over here.

**Comment by mackron** [comment]
I've merged this work into the master branch as part of version 0.9.0. I'm going to go ahead and close this now, but feel free to open a fresh bug report if you experience any bugs.

**Pull request closed without merging**
